using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class HandSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _handData;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class HandSyncModel : RealtimeModel {
    public string handData {
        get {
            return _handDataProperty.value;
        }
        set {
            if (_handDataProperty.value == value) return;
            _handDataProperty.value = value;
            InvalidateReliableLength();
            FireHandDataDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(HandSyncModel model, T value);
    public event PropertyChangedHandler<string> handDataDidChange;
    
    public enum PropertyID : uint {
        HandData = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _handDataProperty;
    
    #endregion
    
    public HandSyncModel() : base(null) {
        _handDataProperty = new ReliableProperty<string>(1, _handData);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _handDataProperty.UnsubscribeCallback();
    }
    
    private void FireHandDataDidChange(string value) {
        try {
            handDataDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _handDataProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _handDataProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.HandData: {
                    changed = _handDataProperty.Read(stream, context);
                    if (changed) FireHandDataDidChange(handData);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _handData = handData;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
